name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: npm run deploy # This runs 'gh-pages -d build'
        env:
          username: ${{ secrets.FTP_USERNAME }}
          # The GITHUB_TOKEN is automatically available to the workflow
          # and given necessary permissions by the 'permissions' block above.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
