name: Deploy to GitHub Pages (Simple)

on:
  push:
    branches: [ "main" ] # Or whatever your main branch is called

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Configure Git User
      run: |
        git config user.email "saleemsiddiqui1996@gmail.com"
        git config user.name "Saleem Siddiqui"

    - name: Deploy
      run: npm run deploy
      env:
        # GITHUB_TOKEN is crucial for gh-pages to push to your repository
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
