name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for gh-pages to push to gh-pages branch
      pages: write     # Required for GitHub Pages deployment
      id-token: write  # Required for GitHub OIDC auth (if using)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Configure Git (for gh-pages)
        run: |
          git config user.name "msaleemsidd"
          git config user.email "saleemsiddiqui1996@gmail.com"

      - name: Deploy to GitHub Pages
        run: |
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}