name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "msaleemsidd"
          git config --global user.email "saleemsiddiqui1996@gmail.com"
          npx gh-pages -d build -r https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/msaleemsidd/msaleemsidd.github.io.git
          # Alternative if above fails:
          # npx gh-pages -d build -r https://${{ secrets.GH_PAT }}@github.com/msaleemsidd/msaleemsidd.github.io.git
